#!/bin/bash

function createManufacturer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/manufacturer.org.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/manufacturer.org.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-manufacturer --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-manufacturer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-manufacturer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-manufacturer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-manufacturer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/manufacturer.org.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy manufacturer's CA cert to manufacturer's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/manufacturer.org.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/manufacturer.org.com/msp/tlscacerts/ca.crt"

  # Copy manufacturer's CA cert to manufacturer's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/manufacturer.org.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/manufacturer.org.com/tlsca/tlsca.manufacturer.org.com-cert.pem"

  # Copy manufacturer's CA cert to manufacturer's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/manufacturer.org.com/ca"
  cp "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/manufacturer.org.com/ca/ca.manufacturer.org.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-manufacturer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-manufacturer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-manufacturer --id.name manufactureradmin --id.secret manufactureradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.org.com/peers/peer0.manufacturer.org.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/manufacturer.org.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/manufacturer.org.com/peers/peer0.manufacturer.org.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.org.com/peers/peer0.manufacturer.org.com/tls" --enrollment.profile tls --csr.hosts peer0.manufacturer.org.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/manufacturer.org.com/peers/peer0.manufacturer.org.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/manufacturer.org.com/peers/peer0.manufacturer.org.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/manufacturer.org.com/peers/peer0.manufacturer.org.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/manufacturer.org.com/peers/peer0.manufacturer.org.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/manufacturer.org.com/peers/peer0.manufacturer.org.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/manufacturer.org.com/peers/peer0.manufacturer.org.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.org.com/users/User1@manufacturer.org.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/manufacturer.org.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/manufacturer.org.com/users/User1@manufacturer.org.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://manufactureradmin:manufactureradminpw@localhost:7054 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.org.com/users/Admin@manufacturer.org.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/manufacturer.org.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/manufacturer.org.com/users/Admin@manufacturer.org.com/msp/config.yaml"
}

function createDealer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/dealer.org.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/dealer.org.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-dealer --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-dealer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-dealer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-dealer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-dealer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/dealer.org.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy dealer's CA cert to dealer's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/dealer.org.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/dealer.org.com/msp/tlscacerts/ca.crt"

  # Copy dealer's CA cert to dealer's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/dealer.org.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/dealer.org.com/tlsca/tlsca.dealer.org.com-cert.pem"

  # Copy dealer's CA cert to dealer's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/dealer.org.com/ca"
  cp "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/dealer.org.com/ca/ca.dealer.org.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-dealer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-dealer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-dealer --id.name dealeradmin --id.secret dealeradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-dealer -M "${PWD}/organizations/peerOrganizations/dealer.org.com/peers/peer0.dealer.org.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/dealer.org.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/dealer.org.com/peers/peer0.dealer.org.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-dealer -M "${PWD}/organizations/peerOrganizations/dealer.org.com/peers/peer0.dealer.org.com/tls" --enrollment.profile tls --csr.hosts peer0.dealer.org.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/dealer.org.com/peers/peer0.dealer.org.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/dealer.org.com/peers/peer0.dealer.org.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/dealer.org.com/peers/peer0.dealer.org.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/dealer.org.com/peers/peer0.dealer.org.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/dealer.org.com/peers/peer0.dealer.org.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/dealer.org.com/peers/peer0.dealer.org.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-dealer -M "${PWD}/organizations/peerOrganizations/dealer.org.com/users/User1@dealer.org.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/dealer.org.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/dealer.org.com/users/User1@dealer.org.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://dealeradmin:dealeradminpw@localhost:8054 --caname ca-dealer -M "${PWD}/organizations/peerOrganizations/dealer.org.com/users/Admin@dealer.org.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/dealer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/dealer.org.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/dealer.org.com/users/Admin@dealer.org.com/msp/config.yaml"
}

function createWholesaler() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/wholesaler.org.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/wholesaler.org.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:10054 --caname ca-wholesaler --tls.certfiles "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-wholesaler.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-wholesaler.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-wholesaler.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-wholesaler.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/wholesaler.org.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy wholesaler's CA cert to wholesaler's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/wholesaler.org.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem" "${PWD}/organizations/peerOrganizations/wholesaler.org.com/msp/tlscacerts/ca.crt"

  # Copy wholesaler's CA cert to wholesaler's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/wholesaler.org.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem" "${PWD}/organizations/peerOrganizations/wholesaler.org.com/tlsca/tlsca.wholesaler.org.com-cert.pem"

  # Copy wholesaler's CA cert to wholesaler's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/wholesaler.org.com/ca"
  cp "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem" "${PWD}/organizations/peerOrganizations/wholesaler.org.com/ca/ca.wholesaler.org.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-wholesaler --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-wholesaler --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-wholesaler --id.name wholesaleradmin --id.secret wholesaleradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-wholesaler -M "${PWD}/organizations/peerOrganizations/wholesaler.org.com/peers/peer0.wholesaler.org.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/wholesaler.org.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/wholesaler.org.com/peers/peer0.wholesaler.org.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-wholesaler -M "${PWD}/organizations/peerOrganizations/wholesaler.org.com/peers/peer0.wholesaler.org.com/tls" --enrollment.profile tls --csr.hosts peer0.wholesaler.org.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/wholesaler.org.com/peers/peer0.wholesaler.org.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/wholesaler.org.com/peers/peer0.wholesaler.org.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/wholesaler.org.com/peers/peer0.wholesaler.org.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/wholesaler.org.com/peers/peer0.wholesaler.org.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/wholesaler.org.com/peers/peer0.wholesaler.org.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/wholesaler.org.com/peers/peer0.wholesaler.org.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:10054 --caname ca-wholesaler -M "${PWD}/organizations/peerOrganizations/wholesaler.org.com/users/User1@wholesaler.org.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/wholesaler.org.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/wholesaler.org.com/users/User1@wholesaler.org.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://wholesaleradmin:wholesaleradminpw@localhost:10054 --caname ca-wholesaler -M "${PWD}/organizations/peerOrganizations/wholesaler.org.com/users/Admin@wholesaler.org.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/wholesaler/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/wholesaler.org.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/wholesaler.org.com/users/Admin@wholesaler.org.com/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/org.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/org.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/org.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/org.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/org.com/msp/tlscacerts/tlsca.org.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/org.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/org.com/tlsca/tlsca.org.com-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/org.com/orderers/orderer.org.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/org.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/org.com/orderers/orderer.org.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/org.com/orderers/orderer.org.com/tls" --enrollment.profile tls --csr.hosts orderer.org.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/org.com/orderers/orderer.org.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/org.com/orderers/orderer.org.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/org.com/orderers/orderer.org.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/org.com/orderers/orderer.org.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/org.com/orderers/orderer.org.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/org.com/orderers/orderer.org.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/org.com/orderers/orderer.org.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/org.com/orderers/orderer.org.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/org.com/orderers/orderer.org.com/msp/tlscacerts/tlsca.org.com-cert.pem"

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/org.com/users/Admin@org.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/org.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/org.com/users/Admin@org.com/msp/config.yaml"
}
